### ISSUE TITLE
[egui::Windows compatibility] Graph rendering stay on top of all egui::Windows 

### ISSUE THREAD

**Issue by deft01** [blitzarx1/egui_graphs#179] opened 2024-02-19 14:12 UTC
Hi, 

Thanks a lot for the quick bug fix that makes compatibility with egui::Windows available.

I have discovered a new bug.

Graph rendering stay on top of all the egui::Windows  even if the Window where the graph is not focused.
I tested different configuration of GraphView, always with the same behavior.

![image](https://github.com/blitzarx1/egui_graphs/assets/10063471/5af6b458-b2ec-4e87-b7f5-6deaa603ab4e)

My versions (using last commit version on master) :

```toml
egui = "0.26.0"
egui_extras = { version = "0.26.0", features = ["svg", "image"]}
eframe = { version = "0.26.0", default-features = false, features = [
    "accesskit",     # Make egui comptaible with screen readers. NOTE: adds a lot of dependencies.
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
    "persistence",   # Enable restoring app state when restarting the app.
] }
egui_tracing = "0.2.1"

serde = { version = "1", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"]}
ron = "0.8"
egui_graphs = { git = "https://github.com/blitzarx1/egui_graphs", branch = "master", features = ["egui_persistence", "serde"]}
```

**Comment by blitzarx1** [comment] 2024-02-19 14:14
Thanks for the report! I know the reason, I will try to fix it today.

**Comment by blitzarx1** [comment] 2024-02-19 14:36
I refused from using egui layer ordering mechanism for ordering graph drawing, because it conflicts with other egui components, which is demonstrated by this bug. 

I returned to simple time ordering and I will keep it this way for now.

**Comment by blitzarx1** [comment] 2024-02-19 14:37
fix is in the master

**Closed by blitzarx1** 2024-02-19 14:37 UTC
Labels: bug

**Comment by oisyn** [comment] 2024-02-20 13:09
I was having the same issue and have been debugging this, only to find out this was being fixed the moment I found the cause.

But alas, #180 still doesn't fix it for us. We render the graph in an egui Window, and it renders the graph under the window.
